INSERT INTO PRODUCTS (STYLE_NUMBER, DESCRIPTION, SIZE, COLOR, PRICE) VALUES('ST1234','WOMENS TOP','XS','Blue',1.79);

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, LINE1, CITY, STATE, ZIP) VALUES ('1234','Shyam','V','shyam@shyam.com','(123)456-7890','123 Hoffman','Seattle','WA','98121');

INSERT INTO ORDERS(ORDER_ID, CUSTOMER_ID, COST) VALUES ('H2-1203', (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE EMAIL = 'shyam@shyam.com'), 3.58);

INSERT INTO ORDER_LINES (ORDER_ID, STYLE_NUMBER, QUANTITY) VALUES ('H2-1203', 'ST1234', 4);
INSERT INTO ORDER_LINES (ORDER_ID, STYLE_NUMBER, QUANTITY) VALUES ('H2-1203', 'ST1234', 2);